Fix kustomze relative path issue.
User encounters the following error message when use kubebuilder to
"make deploy" to their cluster:
Error: rawResources failed to read Resources: Load from path <PROJECT>/config/rbac/rbac_role.yaml failed: security; file '<PROJECT>/config/rbac/rbac_role.yaml' is not in or below '<PROJECT>/config/default'

Root cause is filed in kustomize repo kubernetes-sigs/kustomize#766

This is a temp fix aimed at unblocking kubebuilder users.