fix: golangci-lint passes against a new project
Previously:

deadcode (via golangci-lint) reported:
```
controllers/suite_test.go:23:5: `cfg` is unused (deadcode)
var cfg *rest.Config
    ^
```

errcheck (via golangci-lint) reported:

```
main.go:27:26: Error return value of `nrdbv1alpha1.AddToScheme` is not checked (errcheck)
	nrdbv1alpha1.AddToScheme(scheme)
	                        ^
```

Also add a guardrail or two to the generated_golden.sh script, as it was
not immediately obvious what to do about tar's complaint that it
couldn't recognize the file format.